# Generated by Django 6.0.2 on 2026-03-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date'], name='visits_visit_d_09890f_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['report_date'], name='lab_reports_report__041ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['administered_date'], name='vaccinatio_adminis_5a3ed0_idx'),
        ),
    ]
