# Generated by Django 6.0.3 on 2026-03-05 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_performance_indices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='labreport',
            name='lab_reports_report__041ef8_idx',
        ),
        migrations.RemoveIndex(
            model_name='vaccination',
            name='vaccinatio_adminis_5a3ed0_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visit_d_09890f_idx',
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='administered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
